### ISSUE TITLE
Unable to write to remote FS (OpenSSH 5.2p1/chrooted sftp - subsystem: internal-sftp) when mounted from OS-X Yosemite or Mavericks 

### ISSUE THREAD

**Issue by ph0enix2014** [macfuse/macfuse#170]
When I mount a remote OpenSSH 5.2p1 FS on OS-X Yosemite or Mavericks, it's read-only.  The remote server uses chrooted SFTP set-up where chrooted users are matched to a specific group defined in sshd_config with:

Match Group groupname
        ChrootDirectory /path/to/chrooted/env/%u
        ForceCommand internal-sftp -l VERBOSE
        AllowTcpForwarding no

When I enable SSHFS debugging, I see the following errors being logged:

unique: 2, opcode: LOOKUP (1), nodeid: 1, insize: 44
LOOKUP /._.
[00047] LSTAT
  [00047]         STATUS       33bytes (0ms)
   unique: 2, error: -2 (No such file or directory), outsize: 16
unique: 3, opcode: STATFS (17), nodeid: 1, insize: 40
[00048] EXTENDED
  [00048] EXTENDED_REPLY       97bytes (0ms)
   unique: 3, error: 0 (Undefined error: 0), outsize: 96

The FS mounts without issues when debugging is disabled.  I'm using the SSHFS 2.5.0 with OSXFUSE 2.7.2 binaries from:

http://osxfuse.github.io/

I've tried SSHFS-2.4.1 with osxfuse-2.7.1 as well - same result.

**Comment by bfleischer** [comment]
A new SSHFS build is available on https://macfuse.io. Therefore, I'm closing this issue.
