### ISSUE TITLE
Error -36

### ISSUE THREAD

**Issue by ytzhang0925** [macfuse/macfuse#342]
On my mac running macOS 10.12, I installed osxfuse-3.5.4.dmg and sshfs-2.5.0.pkg, then tried to mount 2 remote ssh connections: one is my private server in Japan, using my root access, while the other server is a public one, which I have no root access.

I mounted the first server in the terminal:

`sudo sshfs -o allow_other,defer_permissions root@xxx.xxx.xxx.xxx:/ /mnt/disk`

The first server seemed to work fine on my Mac.

Then I tried to mount the second server using my user name.

`sudo sshfs -o allow_other,defer_permissions username@xxx.xxx.xxx.xxx:/ /mnt/disk2`

It looked fine when I tried to access the file list from Finder or Terminal. Then I tried to edit a file using Sublime Text 3. Upon saving the text file, the file went to 0 bytes!
Also I tried to copy a file within a directory, but it displayed:

> The Finder can’t complete the operation because some data in “” can’t be read or written.
> (Error code -36)

Any ideas to solve the problem?

**Comment by Wolf00Bomber** [comment]
The same issue is been seen by me when i tried to mount a WD Elements 2TB Drive using the same method.
Error code -36

**Comment by angeagu** [comment]
Same error here trying to mount a 1TB Drive.
Any clue?

**Comment by joaoffalcao** [comment]
Same thing here

**Comment by develsites** [comment]
This issue still hasn't been solved :( I have one WD Elements 1TB also and when I try to mount it by using `sudo /usr/local/bin/ntfs-3g /dev/disk2s1 /Volumes/NTFS -olocal -oallow_other` and copy something to drive after so, it returns `Error code -36`

**Comment by mbakkokom** [comment]
I also have the same problem. But when **I unmount then mount it again**, the copied files appeared fine...

If I want to copy some files after previous copy operation finished, **it will fail**. Again, I just need to unmount then mount it again then do my next batch of copy.

Do we have any workaround for this?

EDIT: You should use Terminal for copying file, moving, removing, etc. I can't reliably use Finder anymore for this.

---

Used command:

    sudo ntfs-3g /dev/disk2s2 /Volumes/ntfs-3g\ default

ntfs-3g version:

    ntfs-3g 2017.3.23 external FUSE 29 - Third Generation NTFS Driver
		Configuration type 1, XATTRS are on, POSIX ACLS are off

**Comment by tuononh** [comment]
Same here on Sierra. As @mbakkokom said, when the error diaglog appear, unmount then click ok. The file will appear just fine.

**Comment by nakarin4350** [comment]
Try Paragon Driver for macOS and it s free for Seagate.

**Comment by kreintjes** [comment]
Same problem over here when mounting an external hard drive with ntfs-3g. When I reconnect the drive (thus remounting it with mac's default ntfs driver), the files do appear as @mbakkokom said. However, when I unmount and mount again with ntfs-3g, the files still don't show up, so I am unable to delete them as well. Any solution would be greatly appreciated.

Versions:
ntfs-3g: 2017.3.23 external FUSE 29
Fuse: 3.7.1
MacOS: High Sierra 10.13.3

I followed the steps in this tutorial for installation/mounting: https://www.howtogeek.com/236055/how-to-write-to-ntfs-drives-on-a-mac/

UPDATE: the files are visible in terminal and can be removed there. In the finder they won't show up, not even after remounting (with FUSE/ntfs-3g).

**Comment by JuliaPoole929Ns** [comment]
Force Close
I’ve run into this sort of a problem from time to time. Quitting and restarting the Finder will often clear up the problem. Sometimes restarting my Mac will suffice.
for more info visit this URL
https://www.errorsolutions.tech/error/mac-error-code-36/

**Comment by RiccardoBellatalla** [comment]
Solved using the "cp" command from command line.

**cp ~/myfile.txt  /Volumes/NTFS**

If you want to check the progress of running "cp" just press CTRL + T

**Comment by jbarros35** [comment]
oh boy that's terrible annoying!

**Comment by pjastrzabek** [comment]
Same issue here..
Mounting external 2TB drive. I have the same "magic" of files appearing or not depending how I mount the drive..

 copying with "mc" was the easiest workaround...

**Comment by yleme** [comment]
Using terminal + rsync worked fine! 

Thanks @kreintjes  and @RiccardoBellatalla

**Comment by ahmadazimi** [comment]
Same issue with Catalina 10.15.4
No updated?

**Comment by bfleischer** [comment]
A new SSHFS build is available on https://macfuse.io/. 

NTFS-3G specific issues should be raised in the NTFS-3G issue tracker.
