### ISSUE TITLE
FUSE Breaks the OpenVPN Connect Client on OSX

### ISSUE THREAD

**Issue by vcardillo** [macfuse/macfuse#360]
I realize that there's going to be little technical information here, because we found no logs to provide. So here's what happens, and please feel free to ask for more details, and I will provide anything I can.

OS X, El Capitan.
openvpn-connect-2.1.3.110.

When FUSE is installed (no drive was mounted in this case), it causes OpenVPN Connect to completely hang the system, at the moment that Connect would successfully connect to a VPN. So, authorization and login still happen fine. After you verify your credentials, instead of connecting to the VPN, the system slowly dies. The VPN never connects, and eventually the Mac turns into a pinwheel of death--but it takes 5-10 minutes for it to grind to a halt.

Let me know how else I can help.

**Comment by bfleischer** [comment]
This might be rated to #358. Are you using other software like VMware, VirtualBox, or Intel HAXM that registers virtual character devices.

**Comment by vcardillo** [comment]
I am using VMware Fusion. However, I restarted a dozen times, and it wasn't running after the restarts. Only removing FUSE solved the problem.
