### ISSUE TITLE
Many failed authentication attempts

### ISSUE THREAD

**Issue by samcunliffe** [macfuse/macfuse#381]
I connect to a remote server using sshfs and osxfuse 3.5.8. Somehow I end up with many (hundreds) of failed authentication attempts of my username which has (rightly) lead to the administrators disabling connections.

The symptoms are exactly described by this post:
https://sourceforge.net/p/fuse/mailman/message/32607460/

```bash
[me@mylocalmachine] $ sshfs --version
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE 3.5.8
FUSE library version: 2.9.7
```

```bash
[me@mylocalmachine]$ ssh me@remote.blah
me@remote.blah's password:
Last failed login: Sat Jun  3 05:43:51 JST 2017 from [MYIPADDRESS] on ssh:notty
There were 225 failed login attempts since the last successful login.
Last login: Wed Feb 15 09:14:21 2017 from [MYIPADDRESS] 
```

**Comment by jstrube** [comment]
I have encountered exactly the same problem. It looks like the sourceforge report is from 2014. Could somebody please comment where this item is on the priority list of the project? For me personally, this is a blocker, since I don't want my account to be disabled just because of this bug.

**Comment by jcjohnson** [comment]
I'm running into the same issue, with OSXFUSE 3.6.3 and SSHFS 2.5 on OSX 10.12.5. Is there any known fix or workaround?

**Comment by mozgit** [comment]
The same problem today.

**Comment by sit23** [comment]
I've just had the same problem with the following versions:
```
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE 3.10.4
FUSE library version: 2.9.7
```
Is this in line to be fixed? Thanks!

**Comment by milicasan** [comment]
Same problem here: keeps getting me blocked from the national supercomputer.

SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE 3.10.4
FUSE library version: 2.9.7
MacOS 10.14.6

It would be great to have this fixed, I am effectively unable to use sshfs.

**Comment by JerryPeng21cuhk** [comment]
Same problem here. The campus network admin reported me the ssh brute force attack coming from my Mac laptop. The reason is the sshfs auto-reconnection behaviour. don't know how to disable it.

**Comment by djhshih** [comment]
Same problem here.

SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
FUSE library version: 2.9.9
MacOS 11.6.4

The network admin notified us yesterday that there were 80,000 ssh requests recently from my workstation to the remote server.
I have been browsing directories with 200-300 files and refreshing the directories for new/updated PDF files as I work.

I have decided to switch to using X11 forwarding and running a X11 PDF viewer on the server instead.

**Comment by bfleischer** [comment]
A new SSHFS build is available on https://macfuse.io/. Therefore, I'm closing this issue.

**Comment by mpmorley** [comment]
Seems like this issue is happening again with the following on MacOS 15. Which results in IP being blacklisted. 

SSHFS version 3.7.3
FUSE library version 3.17.1
using FUSE kernel interface version 7.40
macFUSE mount version 4.10.1
