### ISSUE TITLE
Error code -36 for Sierra 10.12.5 

### ISSUE THREAD

**Issue by mcgyver83** [macfuse/macfuse#401]
Hi, I'm able to read file from an NTFS usb hdd but when I try to copy on the usb NTFS drive a file I always get 
The Finder can’t complete the operation because some data in “abcdefg.rar” can’t be read or written.
(Error code -36)

**Comment by munishkumar631** [comment]
I'm also facing same issue, is someone looking in it?

**Comment by pankajso** [comment]
I'm also facing same issue.

**Comment by bfleischer** [comment]
I'm assuming you are using NTFS-3G. If so, please report the issue on the NTFS-3G support forum at http://tuxera.com/forum/viewforum.php?f=7. NTFS-3G and FUSE for macOS are independent projects. NTFS-3G related issues should first be reported to the NTFS-3G team.

**Comment by wsajosh** [comment]
Same issue here too
