### ISSUE TITLE
SSHFS release on osxfuse homepage is quite old, and is confusing me

### ISSUE THREAD

**Issue by copumpkin** [macfuse/macfuse#404]
From what I see on the homepage, the most recent Mac-native SSHFS release on the osxfuse homepage is from 2014 and is 2.5.0, when the latest sshfs release is 3.2.0 from yesterday. It's unclear (for a new user) if we're supposed to use the old release on the homepage, or compile our own SSHFS, or if there's some incompatibility preventing the latest SSHFS from working on macOS. 

Can the situation be clarified a bit on the homepage? Either by updating the latest release .pkg, explaining why it's old, or by removing it if folks are supposed to be building their own from source.

**Comment by SBUtltmedia** [comment]
I'd like clarification too, I tried to compile sshfs but ran into a fuse3 dependency . A contributor says that osxfuse is based on fuse 2, is this true? https://github.com/libfuse/libfuse/issues/204

**Comment by stgarf** [comment]
Yea, seems it's using libfuse 2.9.7

**Comment by bfleischer** [comment]
A new SSHFS build is available on https://macfuse.io/. This is the latest sshfs release for libfuse 2.
