### ISSUE TITLE
Source code archive doesn't contain code from submodules

### ISSUE THREAD

**Issue by gtimmy** [macfuse/macfuse#413]
Releases tab contains links to the source code, but these archives don't have a code from submodules. Without these directories you are not able to build FUSE, it means that these archives are useless. Does it make sense?

**Comment by pmalhaire** [comment]
It seams like a GitHub issue : [see this](https://stackoverflow.com/questions/34719785/how-to-add-submodule-files-to-a-github-release).

As a workaround if you want to get the code to build a specific release (here 3.7.0)  you can use : 

```bash
git clone --branch osxfuse-3.7.0 --recursive https://github.com/osxfuse/osxfuse.git

**Comment by gtimmy** [comment]
Yes, this command is presented in README.md, but there is no issue to checkout the specific version. The main problem is that these archives are useless for the now and `release.sh` should be updated somehow. This issue is a request for the @bfleischer attention :)
